In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Nelio\Documents\GitHub\canal-ag-teste\data\raw\Clientes.csv')
df

   ID_Cliente              Nome_Cliente               Cidade Estado
0        C001              Enzo Azevedo       Nunes Paulista     AP
1        C002              Miguel Lopes                Sales     MG
2        C003         Laís da Conceição       Cunha de Goiás     SC
3        C004      Maria Alice Ferreira       Nunes da Praia     ES
4        C005        Luiz Gustavo Sales               Barros     AM
5        C006       Pedro Lucas da Cruz    Campos das Flores     MG
6        C007             Letícia Souza        Vieira do Sul     RO
7        C008       Srta. Nina Teixeira      Mendes do Campo     MA
8        C009               Bruna Ramos             Ferreira     PE
9        C010  Luiz Fernando Cavalcanti      Santos do Oeste     BA
10       C011         Sr. Marcelo Souza              Martins     PR
11       C012    Carlos Eduardo Moreira      Duarte do Norte     ES
12       C013         Ana Júlia Cardoso   Campos de Teixeira     SP
13       C014              Cauê Ribeiro             Ferreira     PE
14       C015              Lara da Rosa                 Lima     MG
15       C016              Milena Moura    Silveira de Porto     AM
16       C017       Enzo Gabriel Campos         Aragão Verde     PI
17       C018         Nicolas das Neves              Cardoso     RR
18       C019         Ana Carolina Dias              Azevedo     MT
19       C020       Luiz Gustavo Duarte   Rodrigues do Oeste     PI
20       C021            Thiago Ribeiro              Ribeiro     SE
21       C022           Caroline Castro                Pinto     MS
22       C023             Júlia Rezende               Castro     AL
23       C024            Sabrina Mendes               Farias     DF
24       C025         Luiz Otávio Porto              Pereira     CE
25       C026      Lucas Gabriel Farias                Pires     SE
26       C027          Ana Luiza Barros             Carvalho     SP
27       C028        Davi Luiz Oliveira     Rocha de da Rosa     MG
28       C029      Davi Luiz Nascimento             Nogueira     GO
29       C030            Esther Pereira  da Costa de da Mota     MA
30       C031             Benício Viana                Lopes     AL
31       C032              Nathan Rocha             Caldeira     PE
32       C033              Diego Campos               Duarte     MG
33       C034             Miguel Farias              Cardoso     PA
34       C035      Maria Luiza Silveira    Ferreira do Oeste     RO
35       C036     Sra. Eduarda Ferreira      Costela da Mata     PB
36       C037           Sr. André Ramos              Cardoso     PI
37       C038    Luiz Fernando Ferreira             Monteiro     AP
38       C039          João Lucas Gomes                Pires     TO
39       C040             Rafaela Jesus               Vieira     MA
40       C041           Ana Lívia Cunha     Correia do Campo     SC
41       C042             Brenda Fogaça      da Rocha Alegre     DF
42       C043            Maysa Ferreira  Fernandes de Barros     AP
43       C044              Lara Freitas              Almeida     MT
44       C045     Pedro Miguel Ferreira                Pires     PI
45       C046  Sra. Maria Eduarda Alves              Cardoso     RR
46       C047           Marcelo Azevedo        Vieira Grande     PA
47       C048              Augusto Lima     Barbosa da Praia     DF
48       C049          Elisa Cavalcanti      Oliveira Grande     ES
49       C050             Davi Oliveira               da Luz     SC

In [3]:
df = pd.read_csv(r'C:\Users\Nelio\Documents\GitHub\canal-ag-teste\data\raw\Produtos.csv')
df

   ID_Produto              Nome_Produto    Categoria
0        P001             Tempore Culpa  Eletrônicos
1        P002               Alias Harum  Informática
2        P003         Exercitationem Et  Informática
3        P004         Deserunt Corporis  Eletrônicos
4        P005        Veritatis Quisquam   Escritório
5        P006             Commodi Rerum  Informática
6        P007              Nisi Aliquid  Informática
7        P008       Aliquam Consectetur  Informática
8        P009              Esse Eveniet  Eletrônicos
9        P010                  Quae Sed  Informática
10       P011             Alias Ratione  Eletrônicos
11       P012                Eius Totam  Eletrônicos
12       P013       Voluptates Quisquam  Eletrônicos
13       P014                 Nihil Est  Informática
14       P015     Occaecati Repudiandae  Eletrônicos
15       P016                    Hic Ab   Escritório
16       P017         Dolore Voluptatem  Informática
17       P018           Nisi Laboriosam  Informática
18       P019                 Hic Dolor  Informática
19       P020               Esse Labore  Informática
20       P021      Corporis Consectetur  Informática
21       P022          Modi Consequatur  Eletrônicos
22       P023            Magnam Laborum  Eletrônicos
23       P024                  Sed Fuga  Informática
24       P025           Aperiam Officia  Eletrônicos
25       P026         Quidem Cupiditate  Informática
26       P027              Minus Beatae  Eletrônicos
27       P028              Quod Impedit  Eletrônicos
28       P029                  Sunt Sit  Eletrônicos
29       P030            Magni Repellat  Eletrônicos
30       P031        Earum Voluptatibus   Escritório
31       P032             Atque Aperiam  Informática
32       P033                    Ut Eum   Escritório
33       P034              Illum Beatae  Eletrônicos
34       P035      Eveniet Consequuntur   Escritório
35       P036                  Modi Hic  Informática
36       P037              Odit Tempora  Informática
37       P038           Maiores Dolorem  Eletrônicos
38       P039             Maxime Libero   Escritório
39       P040                 Eos Velit   Escritório
40       P041         Fugiat Voluptates   Escritório
41       P042              Vero Tenetur  Informática
42       P043                 Aut Sequi  Informática
43       P044           Tempora Dolores   Escritório
44       P045  Quibusdam Exercitationem  Informática
45       P046          Dolorem Officiis  Informática
46       P047                Modi Fugit   Escritório
47       P048          Tempore Voluptas  Informática
48       P049                  Quos Est   Escritório
49       P050              Vitae Itaque   Escritório

In [6]:
df = pd.read_csv(r'C:\Users\Nelio\Documents\GitHub\canal-ag-teste\data\raw\Vendas.csv')
df

,ID_Venda,Data,ID_Produto,ID_Cliente,ID_Vendedor,Quantidade,Valor_Unitario
0,1001,2025-02-21,P041,C045,V036,4,358.08
1,1002,2025-05-11,P050,C050,V004,4,419.81
2,1003,2025-05-26,P021,C026,V018,2,144.94
3,1004,2025-03-17,P037,C046,V021,4,344.95
4,1005,2025-02-25,P026,C042,V030,3,169.20
5,1006,2025-05-24,P016,C048,V036,9,168.23
6,1007,2024-12-31,P038,C028,V038,7,212.90
7,1008,2025-04-24,P009,C033,V032,2,390.10
8,1009,2025-05-17,P008,C010,V041,3,406.44
9,1010,2025-03-03,P028,C039,V005,7,221.73
10,1011,2025-02-26,P030,C034,V017,9,437.35
11,1012,2025-01-20,P001,C044,V047,2,356.77
12,1013,2025-04-25,P035,C049,V018,6,100.20
13,1014,2025-01-18,P028,C011,V030,1,479.22
14,1015,2025-05-13,P047,C017,V033,3,278.46
15,1016,2025-04-03,P007,C041,V020,9,324.04
16,1017,2025-01-23,P010,C024,V049,3,292.72
17,1018,2025-04-28,P050,C034,V001,10,195.87
18,1019,2025-05-01,P002,C008,V024,5,157.75
19,1020,2025-03-12,P016,C037,V006,2,379.36
20,1021,2025-03-05,P005,C049,V035,3,107.78
21,1022,2025-04-01,P031,C036,V011,5,287.45
22,1023,2025-01-16,P039,C028,V014,9,389.87
23,1024,2025-01-23,P045,C013,V046,5,229.55
24,1025,2025-02-24,P043,C042,V024,8,454.83
25,1026,2024-12-16,P029,C008,V016,4,78.81
26,1027,2025-04-18,P002,C038,V036,4,314.80
27,1028,2025-01-25,P001,C005,V046,1,153.02
28,1029,2025-01-15,P003,C022,V005,9,157.10
29,1030,2025-01-22,P043,C032,V014,9,109.54
30,1031,2025-02-04,P037,C037,V031,4,403.08
31,1032,2025-02-01,P027,C013,V007,2,346.54
32,1033,2025-05-23,P023,C028,V027,8,438.73
33,1034,2025-03-15,P004,C044,V042,2,77.28
34,1035,2024-12-16,P047,C022,V007,4,136.22
35,1036,2024-12-27,P035,C029,V009,7,132.57
36,1037,2024-12-30,P030,C016,V005,8,413.61
37,1038,2025-01-14,P036,C007,V004,9,426.21
38,1039,2025-02-13,P006,C049,V016,3,232.89
39,1040,2025-04-14,P031,C014,V026,1,124.09
40,1041,2024-12-30,P001,C025,V017,8,178.36
41,1042,2025-04-17,P045,C047,V036,8,119.66
42,1043,2025-01-11,P019,C014,V004,10,381.08
43,1044,2024-12-13,P004,C048,V021,1,72.56
44,1045,2025-02-19,P031,C033,V034,3,75.60
45,1046,2025-02-18,P033,C006,V012,2,317.77
46,1047,2025-02-03,P044,C016,V026,2,473.72
47,1048,2025-03-16,P037,C016,V038,10,67.88
48,1049,2025-03-01,P006,C027,V043,10,304.35
49,1050,2025-02-19,P021,C017,V014,6,157.41

In [5]:
df = pd.read_csv(r'C:\Users\Nelio\Documents\GitHub\canal-ag-teste\data\raw\Vendedores.csv')
df

   ID_Vendedor                Nome_Vendedor         Equipe
0         V001              Dr. Raul Farias  Equipe Centro
1         V002        Davi Lucca Cavalcanti     Equipe Sul
2         V003               Alícia Ribeiro   Equipe Norte
3         V004                Eduardo Ramos  Equipe Centro
4         V005           Dr. Enzo das Neves     Equipe Sul
5         V006               Rafael da Mota  Equipe Centro
6         V007               Helena Freitas   Equipe Norte
7         V008                Vitor Freitas     Equipe Sul
8         V009           Dr. Renan Teixeira   Equipe Norte
9         V010  Sr. Carlos Eduardo Ferreira  Equipe Centro
10        V011              Nathan Ferreira     Equipe Sul
11        V012                 Calebe Pinto  Equipe Centro
12        V013            Dr. Leandro Silva  Equipe Centro
13        V014           João Pedro da Mota     Equipe Sul
14        V015                Augusto Pinto  Equipe Centro
15        V016       Luiz Henrique Teixeira   Equipe Norte
16        V017                Rebeca da Paz  Equipe Centro
17        V018            Dr. Bernardo Melo   Equipe Norte
18        V019              Gabrielly Costa   Equipe Norte
19        V020              Sra. Lívia Lima  Equipe Centro
20        V021                Júlia Martins   Equipe Norte
21        V022             Pietra Gonçalves     Equipe Sul
22        V023                  Ana da Mota   Equipe Norte
23        V024           Natália Nascimento   Equipe Norte
24        V025                 Sofia da Luz   Equipe Norte
25        V026         Maria Fernanda Jesus     Equipe Sul
26        V027          Maria Clara Almeida     Equipe Sul
27        V028    Gustavo Henrique da Rocha     Equipe Sul
28        V029            Valentina Martins  Equipe Centro
29        V030                  Laura Pires     Equipe Sul
30        V031                  Clara Silva   Equipe Norte
31        V032             Vitória da Cunha     Equipe Sul
32        V033              Ana Júlia Gomes     Equipe Sul
33        V034                 Mirella Melo   Equipe Norte
34        V035         Vitor Gabriel Duarte  Equipe Centro
35        V036           Gabriela das Neves     Equipe Sul
36        V037                Danilo Araújo  Equipe Centro
37        V038               Felipe Ribeiro  Equipe Centro
38        V039               Stella Cardoso  Equipe Centro
39        V040              Kamilly da Mota   Equipe Norte
40        V041             Dra. Joana Sales  Equipe Centro
41        V042           Elisa da Conceição  Equipe Centro
42        V043               Olivia Almeida   Equipe Norte
43        V044                 Yago Pereira  Equipe Centro
44        V045                Davi Silveira  Equipe Centro
45        V046           Ana Beatriz Farias   Equipe Norte
46        V047                Lorenzo Cunha   Equipe Norte
47        V048                Natália Souza     Equipe Sul
48        V049          Maria Vitória Lopes     Equipe Sul
49        V050               Mariana Santos     Equipe Sul